version: '3.3'

networks:
  network-mguirola201700772:
    driver: bridge

services:

  mysql:
    image: mysql:latest
    container_name: mguirola201700772-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - network-mguirola201700772

  api:
    image: miguelguirola/mguirola201700772-api
    container_name: mguirola201700772-api
    restart: always
    depends_on:
      - mysql
    ports:
      - "4000:4000"
    networks:
      - network-mguirola201700772

  frontend:
    image: miguelguirola/mguirola201700772-front
    container_name: mguirola201700772-front
    links: 
      - api
    restart: always
    ports:
      - "80:3000"
    networks:
      - network-mguirola201700772